Patch warning note endpoint
LBHackney-IT/social-care-case-viewer-api pull request #209
Opened 2021-04-20 15:25 UTC by LBHBReynolds-Carr

## Link to JIRA ticket

https://hackney.atlassian.net/browse/SCS-705

## Describe this PR

### *What is the problem we're trying to solve*

As a user, I want to update Warning Notes in response to a review

### *What changes have we introduced*

- Added PatchWarningNoteRequest
- Added schema for sccv_Warning_note_review table
- Added WarningNoteReview infrastructure object
- Added PatchWarningNote method to gateway with no response
- Created PostNoteReview method to gateway with no response
- Created PatchWarningNote method in gateway
- Created PostWarningNoteReview method in gateway
- PostWarningNoteReview only exists as a method for PatchWarningNote
- Created ExecutePatch method in WarningNoteUseCase
- Created PatchWarningNote method in controller
- Hard coded PostWarningNote method in gateway to set status to open

#### _Checklist_

- [x] Added tests to cover all new production code
- [x] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [x] Checked all code for possible refactoring
- [x] Code pipeline builds correctly

### *Follow up actions after merging PR*

Get PostWarningNoteReview

2021-04-20 16:02 UTC, JohnFarrellDev commented
In future can we keep individual commits shorter and more frequent, commit per each bit of useful functionality such as a single new gateway etc.

2021-04-20 17:02 UTC, JohnFarrellDev requested changes
I'd be happy to go through this with you tomorrow to help and explain any of these suggested changes.

2021-04-20 17:02 UTC, JohnFarrellDev commented on SocialCareCaseViewerApi/V1/Boundary/Requests/PatchWarningNoteRequest.cs
> +    public class PatchWarningNoteRequest
Can we make use of FluentValidation here similar to `CreateAllocationRequest`?

2021-04-20 17:14 UTC, JohnFarrellDev commented
We must add the use case to our Startup.cs, if we also create a validation class it is required in Startup.cs

2021-04-21 08:26 UTC, LBHBReynolds-Carr commented on .editorconfig
> +# delete before deployment
Good job I left that comment! Deleted.

2021-04-21 08:39 UTC, LBHBReynolds-Carr commented on SocialCareCaseViewerApi/V1/Controllers/SocialCareCaseViewerApiController.cs
> +            _warningNoteUseCase.ExecutePatch(request);
I've added a 404 response

2021-04-21 08:44 UTC, LBHBReynolds-Carr commented on SocialCareCaseViewerApi/V1/Exceptions/CustomExceptions.cs
> +    public class PostWarningNoteReviewException : Exception
Removed

2021-04-21 08:46 UTC, LBHBReynolds-Carr commented on terraform/production/.editorconfig
> +[*]
I'm not entirely sure why this entire document is reading as being changed, this matches what's currently in the editor config on the dev branch

2021-04-21 09:39 UTC, LBHBReynolds-Carr commented on SocialCareCaseViewerApi.Tests/V1/Controllers/SocialCareCaseViewerApiControllerTests.cs
> +        [Test]
Testing for 404 catch added

2021-04-21 12:21 UTC, LBHBReynolds-Carr commented on SocialCareCaseViewerApi.Tests/V1/Gateways/DatabaseGateway.Tests.cs
> +            Person stubbedPerson = CreateStubbedPerson();
TestHelpers.CreatePerson() now utilised

2021-04-21 12:22 UTC, LBHBReynolds-Carr commented on SocialCareCaseViewerApi.Tests/V1/Gateways/DatabaseGateway.Tests.cs
> +            stubbedPerson = SavePersonToDatabase(stubbedPerson);
TestHelpers.CreatePerson() now utilised

2021-04-21 12:22 UTC, LBHBReynolds-Carr commented on SocialCareCaseViewerApi.Tests/V1/Gateways/DatabaseGateway.Tests.cs
> +            Person stubbedPerson = CreateStubbedPerson();
TestHelpers.CreatePatchWarningNoteRequest and TestHelpers.CreateWarningNote created and implemented

2021-04-21 18:57 UTC, JohnFarrellDev submitted a review, later dismissed
Looks good to go

2021-04-22 09:02 UTC, Renny4Real requested changes
We don't want to merge into development until development goes into master first

2021-04-22 14:06 UTC, JohnFarrellDev approved these changes
Re-approve for deployment process

2021-04-22 14:06 UTC, Renny4Real approved these changes

2021-04-22 14:06 UTC, merged